owner: digitalservice4germany
repo: uptime-monitor

sites:
  - name: Grundsteuer
    url: https://www.grundsteuererklaerung-fuer-privateigentum.de
    icon: https://www.grundsteuererklaerung-fuer-privateigentum.de/favicon.ico
    maxResponseTime: 5000
    assignees:
      - nfelger
      - joschka
      - shrzaf
      - frederike-ramin

  - name: DigitalService Website
    url: https://digitalservice.bund.de/

  - name: Agora
    url: https://agora-oegd.de
    icon: https://nutzerinnenverwaltung.agora-oegd.de/auth/resources/72dib/login/agora/img/favicon.ico
    __dangerous__disable_verify_peer: true
    expectedStatusCodes:
      - 200
      - 302
    assignees:
      - zechmeister

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DigitalService status
  introTitle: "**DigitalService** Service Status"
  introMessage: Für ein digitales Deutschland
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/digitalservice4germany`
    - title: Webseite
      href: https://digitalservice.bund.de/
