owner: digitalservice4germany
repo: uptime-monitor

sites:
  - name: Grundsteuer
    url: https://www.grundsteuererklaerung-fuer-privateigentum.de
  - name: test failing site
    url: https://www.grundsteuererklaerung-fuer-privateigentum.de/123
