name: OpsGenie Webhook on Down Service Issue

on:
  issues:
    types:
      - opened

jobs:
  trigger_opsgenie:
    runs-on: ubuntu-latest

    steps:
    - name: Check Issue Title and Trigger OpsGenie
      env:
        A2J_OPSGENIE_WEBHOOK_URL: ${{ secrets.A2J_OPSGENIE_WEBHOOK_URL }}
      if: contains(github.event.issue.title, 'service.justiz.de is down')
      run: |
        echo "Creating OpsGenie alert for 'service.justiz.de is down' issue..."
        curl -X POST -H "Content-Type: application/json" -d '{"message": "service.justiz.de is down", "alias": "${{ github.event.issue.number }}", "source": "uptime"}' $A2J_OPSGENIE_WEBHOOK_URL
